name: shipping-roberta
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch>=2.1
      - transformers>=4.40
      - datasets>=2.19
      - scikit-learn>=1.3
      - numpy>=1.24
      - pandas>=1.5
      - accelerate>=0.31
      - tensorboard>=2.14
      - wandb>=0.16

